---
ansible_sudo_pass: 'AsDn*+y5B$K4'
ansible_user: nagios
ansible_password: 'AsDn*+y5B$K4'
ssl_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA9D/WSRJWuTrDUuY4gvhDtl0O7WJBWqI2ImwK6Djk46r7GSUf
  XcIh2ErjtW+FWVLhHAqAc54tpfd4a285LEma3juTiUyVhr5HTRuVLtuA8FwmX1uG
  iJuOO3CYIe3u7BW128j0icEFcTEAlEi7MvxuWqcsiGgCZVC3n4RhEBoZNOqcubnT
  ZEFNWZ6iu7VXBJPzzlRZKDBNwlkOE0ZePv6iwceRg5SnNtT6irubLR9N0Xu4u2cr
  HD23RhvXbHRKk+/no8C3yX5ffVM/cvycGr+9IarpKfheDfWG8mSRVH4f9Igc9D3p
  FT0Ylk47lhDBM0FIwsNM5tSq6YAL2xVuMV6DV/oj0lYMjKeQgSD00PhFRPK4d4Uf
  ZqXSXjCbeBp63CKmYo12x7d1aq+PywK7FO+X20/AIK6+0U6++ZTOZb7DT5vi0W3W
  +6lL+Kx3WVuXkuIS/4nTGURb6qMtxAV7RHtMQ9wZoVWGhVbwqUOpTImy4cN6XeLe
  zPHG2wiE/55doGYBpv05rdWXbTipV2EP5DSnVBz/IJqQ5Ey35mzZs5mB2snvdtoR
  yKSASV8bYReAtjMwn00DQWYkwaI/gGmRGkMCkxdRkagYlwWcTnYujBJhpdTV3nrs
  LzRkLOwN6iNRneNB5m3jmIRjLCKuIJJR7JGZXyhay8g8nMESwDBw/RMiL6UCAwEA
  AQKCAgEA3VgImlm7K8tb/QFTTyUrP9VfVLLJJRiBVHpy+/WrP8LQIP5qSW5He5qK
  dv7kaolYJTBDLgO3vILipwG5XzAo36I/1poHm39OYEtRy4/ybmAkCiCIb74AjE9C
  HuVfsqUOFGotabT5eJV+v+KVeuQWIaMEEW2oViZq8W1nBM+R7kl61DjZoC4pqcDA
  GrmAbU6jEGWSEoCLx0crIT6Q5CegWVnAvex2CJPDpPvU6XRH8kJbq8EX6VTohOlw
  NQHCIAS198kLBNe4M3vAsTTJRthhzmPzPyysF5xcucd3iIlv7gt3qcN9OdkPMg8d
  oqX2X7uW86FHTJyHcmmu1NC79pN/E/MDdcKNYtTXPg3r+Rz9l/RJ0Q+gmDDZfYqc
  1BKK7Rzedbu1LJtczjmu1DGfEhmxQ9DFS0kbwFZv8l6LgDRIIeYFNvpI3NtAMmED
  giJXkbrUJEH5tKhQanUYsVUjplhjHCRMoqfGi33zfdmJ0ji5HXa2mRN1FcBwLTT2
  VEOgjAKfhX3n93+PM/3T44VEPh3/pKlK+j8in04JPb8vdXV0iisn2iQiHMxhNJAT
  9mzpBSDnplOxWqo4MGAOL715XBikmEkgDs4WI2cDGDDPMSH79+8t3wmW8p3R74tk
  uzkgfXm0iI1P/wRVwkTmP1C+Mhwu6YVfQMdgXcax1miaSkymo4ECggEBAP05g1PT
  5piME3urMqVrtl3ZfpSgr9Edz03gzzTgMpR5j//Y+q6N28CF4kIhQS8C6+h1C7Gf
  BtP+mXykmxTtwtTV8I97/NNhAo9M/XdEV3eR0HyfI3BMpf6RmXYCUDHbWg6kbyGv
  9dObVIQQ1B70DAGu5lzA3IHYZ/+QAc4ctPceaye5qwMrOTiACo87z2WZGELKoiFn
  VawtS1UPOOIb8ERQI4q8+u3shDzWOhaFWit37RqLsilRDzHpRzApJJ2qFn7g8gHi
  9Rktx7f8RAXzVBHRXgSdSlOdCgFMAHnZrMIx+QlQpTADwENB+OzFbE1NplOChxnA
  6qTrI9e5WFlwnAUCggEBAPbtJDyBkPvq4p3i739gsW6H4zaIOUeJRFYn/ZPnjZPM
  Nv1QCiVD6kT2W5AMFae/daWgMfuzmy0ZGyxKBY/YYHPumh6aWFUTLMPKGRtf70Do
  3tn4MY/hpufHUxnDgDYkMJzCeTTLTytWEsOxIIMlMHmMMNzsewcfu1z6R4R7SMZG
  VYN711LCDSRfqEF/278YXEVzJd9G1ONtmhqgVWj8wI2AcKRwegu+EGoBkkuEBEzx
  g9doEhYjI8e6ZOqFTWs8/ajA3d19qFC1B+00RM+IbYznyyJCaQK1BKS/GYVq3IvK
  3EJ2nMZkkvPUgCKhcRIoK8NfECFslS/TKAGpQXYFNyECggEAFVYNPLj0CxJyac8o
  +0syGIJE6h0H82TBnNw+WUQyvtPnUDVmGeMWCwi84bmPlnh2jCWgkJzHpIElSZ1M
  +9x0uB42oMBfsyfPYWepS61UeVyt5nI6ODIdIm/+MDVNsIW89tLgEkSTP/ssidwp
  I1qI0HN+MX6GleI4EQ5/OHCuxsunV7eLMz8nGR2gxiTR+suFgcs1Ef909obye/5G
  Wrbj7b2a4Qu/UODG26FpT5B44oS+U6hFoLmVwCzZtLMixK4aKyKlAYewAykaVORK
  jv3LrZyogVcHdjgbKbTPrXSr28j+JMzIvlzyjDg40ypnT7QlOZAb9g2NN8wgPwL8
  8LxOSQKCAQBCRkfxjX0SgGquodhSQeudlQ9g9ZMaJjeXQEiJSB7xymAAAVmXwvC/
  7beJpBSz32l+OM7xlbVSl2h5rKxtfU/2DdaD3D1VKD5dloLCnC8lJtuZeUokKhaY
  IyGkyppA7dm2WWQazW7EXOfQalwllve5x+zdfwNOWC/7tpk3b7eKsBoHnleeuMK6
  Pop0ehLK6YjqgwtpMCO3nxU7jEkgUqaD1DNnj2DSggL50M4pQpe85x3R1Pb1xhy2
  YMrxPzIWVFpozss9xZpFfzFPczX81ctBhH07BsQUm+1RIpGBA7uKMbqIhDlz7k6a
  7zAtG1Oz4eBNIdi8f95S5cPZHkqZmLDBAoIBAQDgnmyaaQ4rvTRe7bbRrpKDHwDR
  zeed44FIoGWCzGKtAQRmeSR0PF7eEB9Z2L1RCXadS3qw3TPkV4rYdDyzX9l1MpLH
  Zed9TYI8nAeY7ovU6ebKGi0KFhGHCMCxFW+O5q06LRtyPHA6pi8qQ31aIf4Rfr9K
  x8cX5wmqCs/+J+fODS6ycwGzq82qoLvEVPxpPtaGfJIskh4m0lwRifmntTp4sFu8
  puWuwwn4POV8PAAvssSissL0LIsZLoukQwIo1SvW4tq2rOqR8cMDPPlQsashhZe1
  2xuhunYyUkKHrThFENAb3R13QPTJ6DCkAUrRPV9ZmAJg22kpPIUymh6BoFTD
  -----END RSA PRIVATE KEY-----